import type { Service, ServiceCategory, Event } from "@/types/database";

export const sampleCategories: ServiceCategory[] = [
  {
    id: "cat-1",
    name: "Puja & Shanti",
    slug: "puja-shanti",
    description:
      "Purification, blessing, and auspicious pujas for homes, families, and milestones",
    icon: "🙏",
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-2",
    name: "Parayanam & Devotion",
    slug: "parayanam-devotion",
    description:
      "Sacred recitations and devotional observances rooted in Puranic and Vedic tradition",
    icon: "📿",
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-3",
    name: "Shraddham & Ancestor Rites",
    slug: "shraddham-ancestor-rites",
    description:
      "Traditional rites for honoring ancestors with Vaidika procedure and reverence",
    icon: "🪔",
    sort_order: 3,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-4",
    name: "Kalyanam & Weddings",
    slug: "kalyanam-weddings",
    description:
      "Divine weddings and auspicious ceremonial celebrations for deities and families",
    icon: "💒",
    sort_order: 4,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-5",
    name: "Rudrabhishekam & Abhishekam",
    slug: "rudrabhishekam-abhishekam",
    description:
      "Elaborate Shiva worship, Vedic chant, and abhishekam traditions",
    icon: "🔥",
    sort_order: 5,
    created_at: "2024-01-01T00:00:00.000Z",
  },
];

export const sampleServices: Service[] = [
  {
    id: "svc-1",
    category_id: "cat-1",
    name: "Udaka Shanthi Puja",
    slug: "udaka-shanthi-puja",
    short_description:
      "A Vedic purification ritual performed to sanctify a home, family, or auspicious occasion.",
    full_description:
      "Udaka Shanthi Puja is a traditional purification ceremony centered on sanctified water, Vedic mantra, and kalasha worship. It is commonly performed before major milestones, new beginnings, and important family ceremonies to invoke harmony, cleanliness, and divine grace.",
    significance:
      "This puja is believed to cleanse subtle negativity, prepare the environment for auspicious activity, and invite blessings of peace and protection.",
    items_to_bring: [
      "Kalasham or vessel for sanctified water",
      "Mango leaves and coconut",
      "Turmeric, kumkum, and flowers",
      "Fruits and betel leaves",
    ],
    whats_included: [
      "Sankalpam and kalasha sthapanam",
      "Udaka shanthi mantra recitation",
      "Household or event blessing",
      "Prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-2",
    category_id: "cat-2",
    name: "Devi Saptashati Parayanam",
    slug: "devi-saptashati-parayanam",
    short_description:
      "Full devotional recitation of the Durga Saptashati for protection, courage, and divine grace.",
    full_description:
      "Devi Saptashati Parayanam is the sacred chanting of the 700 verses of the Markandeya Purana glorifying Goddess Durga in her victorious and compassionate forms. It is traditionally performed during Navaratri, on special vows, or when seeking inner strength and spiritual protection.",
    significance:
      "The parayanam is revered for removing fear, strengthening resolve, and invoking the blessings of the Divine Mother.",
    items_to_bring: [
      "Kumkum and turmeric",
      "Fresh flowers",
      "Fruits and naivedyam",
      "Devi photo or vigraham if performed at home",
    ],
    whats_included: [
      "Sankalpam",
      "Structured Devi Saptashati chanting",
      "Devi upacharas",
      "Closing prayers and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-3",
    category_id: "cat-2",
    name: "Sundarakanda Path (Parayanam)",
    slug: "sundarakanda-path-parayanam",
    short_description:
      "Sacred recitation of Sundarakanda for courage, protection, and the graceful removal of obstacles.",
    full_description:
      "Sundarakanda Path is the devotional recitation of the Sundarakanda section of the Ramayana, celebrating Hanuman's strength, devotion, and divine success. Families often sponsor this parayanam during challenging periods, before major undertakings, or in gratitude for answered prayers.",
    significance:
      "This path is traditionally associated with courage, confidence, wellbeing, and forward movement through difficult situations.",
    items_to_bring: [
      "Hanuman or Rama photo",
      "Flowers and betel leaves",
      "Fruits or naivedyam",
      "Ghee lamp",
    ],
    whats_included: [
      "Sankalpam",
      "Guided Sundarakanda recitation",
      "Hanuman prayers",
      "Mangala harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 150,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-4",
    category_id: "cat-3",
    name: "Anna Shraddham",
    slug: "anna-shraddham",
    short_description:
      "Traditional Vaidika ancestor rite with cooked offerings and reverential remembrance.",
    full_description:
      "Anna Shraddham is the classical annual ancestor ceremony performed with cooked food offerings, tarpana, and prescribed Vedic procedure. It is observed to honor departed parents and forefathers with devotion, gratitude, and continuity of family dharma.",
    significance:
      "The rite expresses remembrance, filial duty, and prayers for the peace and upliftment of ancestors.",
    items_to_bring: [
      "Cooked offering materials as advised",
      "Sesame seeds and darbha",
      "Vastra or dakshina",
      "Banana leaves, fruits, and betel leaves",
    ],
    whats_included: [
      "Sankalpam",
      "Pitru tarpana guidance",
      "Full shraddham procedure",
      "Concluding blessings",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-5",
    category_id: "cat-3",
    name: "Hiranya Shraddham",
    slug: "hiranya-shraddham",
    short_description:
      "A simplified Vaidika shraddham observance centered on dakshina and prescribed offerings.",
    full_description:
      "Hiranya Shraddham is performed when a full anna shraddham is not practical or when tradition calls for a dakshina-based observance. The rite is carried out with mantra, tarpana, and respectful offering in accordance with Vaidika guidance.",
    significance:
      "This ceremony preserves ancestral observance with sincerity and scriptural discipline even in constrained circumstances.",
    items_to_bring: [
      "Sesame seeds and darbha",
      "Dakshina or hiranya offering",
      "Fruits and betel leaves",
      "Required ritual items as advised",
    ],
    whats_included: [
      "Sankalpam",
      "Pitru rituals and tarpana",
      "Hiranya-based offering procedure",
      "Closing prayers",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-6",
    category_id: "cat-4",
    name: "Shiva Parvati Kalyanam",
    slug: "shiva-parvati-kalyanam",
    short_description:
      "Celestial wedding ceremony of Lord Shiva and Goddess Parvati performed with devotion and Vedic tradition.",
    full_description:
      "Shiva Parvati Kalyanam celebrates the divine union of Shiva and Parvati through auspicious kalyana rituals, mantra, and ceremonial offerings. It is often sponsored for marital harmony, family wellbeing, and divine blessings in household life.",
    significance:
      "Witnessing or sponsoring this kalyanam is believed to invite grace, unity, and auspiciousness into family relationships.",
    items_to_bring: [
      "Flowers and garlands",
      "Fruits and coconuts",
      "New vastram for deities if desired",
      "Naivedyam offerings",
    ],
    whats_included: [
      "Sankalpam",
      "Complete kalyanam procedure",
      "Mangalya and talambralu rituals",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-7",
    category_id: "cat-5",
    name: "Mahanyasa Purvaka Ekadasa Rudrabhishekam",
    slug: "mahanyasa-purvaka-ekadasa-rudrabhishekam",
    short_description:
      "An elaborate Shiva abhishekam with Mahanyasam and repeated Sri Rudram chanting.",
    full_description:
      "Mahanyasa Purvaka Ekadasa Rudrabhishekam is a deeply revered Shiva ritual in which Mahanyasam is performed before Ekadasa repetition of Sri Rudram and sacred abhishekam offerings. It is commonly sponsored for spiritual upliftment, family welfare, health, and the removal of karmic obstacles.",
    significance:
      "This worship is considered especially powerful for peace, purification, devotion to Lord Shiva, and the invocation of profound spiritual grace.",
    items_to_bring: [
      "Milk, curd, honey, and other abhishekam dravyas as advised",
      "Bilva leaves and flowers",
      "Fruits, coconuts, and naivedyam",
      "Vastra or dakshina",
    ],
    whats_included: [
      "Mahanyasam",
      "Ekadasa Sri Rudram chanting",
      "Abhishekam and archana",
      "Mangala harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 210,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
];

export const sampleEvents: Event[] = [
  {
    id: "evt-1",
    title: "Ugadi Celebrations 2026",
    description:
      "Telugu and Kannada New Year celebrations with special poojas, cultural programs, and festive feast. Join us for Panchangam Sravanam and Ugadi Pachadi distribution.",
    event_type: "festival",
    start_date: "2026-03-29",
    end_date: "2026-03-29",
    start_time: "09:00",
    end_time: "14:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 45,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-2",
    title: "Sri Rama Navami",
    description:
      "Celebration of Lord Rama's birth with Sita Rama Kalyanotsavam, Abhishekam, and special cultural programs throughout the day.",
    event_type: "festival",
    start_date: "2026-04-07",
    end_date: "2026-04-07",
    start_time: "08:00",
    end_time: "20:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 78,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-3",
    title: "Weekly Bhajan Sandhya",
    description:
      "Join us every Saturday evening for devotional bhajans and kirtans. All are welcome to participate and immerse in the divine melodies.",
    event_type: "regular_pooja",
    start_date: "2026-03-14",
    end_date: null,
    start_time: "18:00",
    end_time: "19:30",
    location: "RNHT Prayer Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-saturday",
    rsvp_enabled: false,
    rsvp_count: 0,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-4",
    title: "Yoga & Meditation Session",
    description:
      "Weekly yoga and meditation classes suitable for all levels. Guided by certified instructors combining traditional and modern techniques.",
    event_type: "class",
    start_date: "2026-03-15",
    end_date: null,
    start_time: "07:00",
    end_time: "08:30",
    location: "RNHT Community Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-sunday",
    rsvp_enabled: true,
    rsvp_count: 22,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-5",
    title: "Monthly Satyanarayana Vratam",
    description:
      "Join the community for the monthly Satyanarayana Pooja on Purnima (Full Moon) day. Katha recitation followed by maha prasadam.",
    event_type: "regular_pooja",
    start_date: "2026-03-25",
    end_date: null,
    start_time: "10:00",
    end_time: "12:30",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-purnima",
    rsvp_enabled: true,
    rsvp_count: 35,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-6",
    title: "Community Annadanam",
    description:
      "Monthly community meal service open to all. Volunteer to cook and serve or simply join us for a blessed meal.",
    event_type: "community",
    start_date: "2026-03-22",
    end_date: null,
    start_time: "12:00",
    end_time: "14:00",
    location: "RNHT Dining Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-4th-sunday",
    rsvp_enabled: true,
    rsvp_count: 60,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-7",
    title: "Hanuman Jayanti",
    description:
      "Grand celebration of Lord Hanuman's birth with special Abhishekam, Sundara Kandam Parayanam, and cultural events.",
    event_type: "festival",
    start_date: "2026-04-13",
    end_date: "2026-04-13",
    start_time: "06:00",
    end_time: "21:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 55,
    created_at: "2024-01-01T00:00:00.000Z",
  },
];

export const samplePanchangam = {
  date: "2024-01-01",
  location: "Austin, TX",
  sunrise: "6:22 AM",
  sunset: "6:01 PM",
  tithi: {
    name: "Dwadashi",
    start: "3:45 AM",
    end: "2:12 AM (next day)",
    paksha: "Shukla",
  },
  nakshatra: {
    name: "Pushya",
    start: "11:23 PM (prev day)",
    end: "10:45 PM",
  },
  yoga: {
    name: "Siddha",
    start: "6:15 AM",
    end: "4:33 AM (next day)",
  },
  karana: {
    name: "Baalava",
    start: "3:45 AM",
    end: "3:02 PM",
  },
  rahu_kalam: {
    start: "10:42 AM",
    end: "12:12 PM",
    warning: true,
  },
  yama_gandam: {
    start: "3:12 PM",
    end: "4:42 PM",
  },
  gulika_kalam: {
    start: "7:42 AM",
    end: "9:12 AM",
  },
  muhurtham: {
    name: "Abhijit Muhurtham",
    start: "11:47 AM",
    end: "12:37 PM",
  },
  festival: null as { name: string; description: string } | null,
  vaara: "Wednesday",
  masa: "Phalguna",
  samvatsara: "Krodhana",
};
