import type { Service, ServiceCategory, Event } from "@/types/database";

export const sampleCategories: ServiceCategory[] = [
  {
    id: "cat-1",
    name: "Puja & Shanti",
    slug: "puja-shanti",
    description:
      "Purification, blessing, and auspicious pujas for homes, families, and milestones",
    icon: "🙏",
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-2",
    name: "Parayanam & Devotion",
    slug: "parayanam-devotion",
    description:
      "Sacred recitations and devotional observances rooted in Puranic and Vedic tradition",
    icon: "📿",
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-3",
    name: "Shraddham & Ancestor Rites",
    slug: "shraddham-ancestor-rites",
    description:
      "Traditional rites for honoring ancestors with Vaidika procedure and reverence",
    icon: "🪔",
    sort_order: 3,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-4",
    name: "Kalyanam & Weddings",
    slug: "kalyanam-weddings",
    description:
      "Divine weddings and auspicious ceremonial celebrations for deities and families",
    icon: "🪷",
    sort_order: 4,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-5",
    name: "Rudrabhishekam & Abhishekam",
    slug: "rudrabhishekam-abhishekam",
    description:
      "Elaborate Shiva worship, Vedic chant, and abhishekam traditions",
    icon: "🔥",
    sort_order: 5,
    created_at: "2024-01-01T00:00:00.000Z",
  },
];

export const sampleServices: Service[] = [
  {
    id: "svc-1",
    category_id: "cat-1",
    name: "UDAKA SHANTHI PUJA",
    slug: "udaka-shanthi-puja",
    short_description:
      "A powerful Vedic water purification ritual for peace, healing, graha dosha shanti, and spiritual balance.",
    full_description:
      "Udaka Shanti Puja is a powerful Vedic ritual in which sacred, mantra-charged water is used to pacify negative energies and restore peace, health, and harmony. It is performed for the removal of graha doshas, especially those related to Rahu, Ketu, and Shani, and is commonly observed after birth, before important life events, during difficult planetary periods, or following repeated obstacles or ill health. It is also performed for everyone's well-being after a death in the family, to remove ritual impurity, and for the purification of the body and house premises. The ritual includes sankalpam, kalasha sthapanam, and Vedic mantra recitation, sometimes accompanied by a shanti homa, after which the sanctified water is sprinkled for purification.",
    significance:
      "This puja is believed to cleanse the body, mind, and surroundings while bringing spiritual balance, protection, harmony, and lasting inner peace.",
    items_to_bring: [
      "Kalasham or vessel for sanctified water",
      "Mango leaves, coconut, and flowers",
      "Turmeric, kumkum, and fruits",
      "Any additional items advised by Panditji based on family or graha shanti needs",
    ],
    whats_included: [
      "Sankalpam and kalasha sthapanam",
      "Vedic mantra recitation for shanti and purification",
      "Sanctified water sprinkling for body and premises",
      "Optional shanti homa guidance when required",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-2",
    category_id: "cat-2",
    name: "CHANDI PARAYANAM / CHANDI PATH",
    slug: "devi-saptashati-parayanam",
    short_description:
      "A sacred Chandi Path of 700 verses invoking the Divine Mother for courage, protection, peace, and spiritual harmony.",
    full_description:
      "Durga Saptashati Path, also known as Devi Mahatmya or Chandi Path, is a sacred recitation of 700 verses that praise the Divine Mother as the supreme universal power behind creation, protection, and transformation. Preserved in the Markandeya Purana and central to the Shakta tradition, the text is divided into 13 chapters and three main sections describing the Mother's victory over forces representing ignorance, ego, desire, and subtle pride. Chandi Devi is worshipped here as both fierce and compassionate, destroying negativity and injustice while granting protection, strength, wisdom, and prosperity to her devotees. The path is traditionally performed with preparatory prayers such as sankalpa, nyasa, kavacha, argala, and keelaka, followed by complete recitation, making it a powerful spiritual discipline rather than just a story. It is especially observed during Navaratri, difficult phases of life, major transitions, and for family well-being.",
    significance:
      "This sacred path is believed to bring courage, peace, protection from unseen forces, removal of doshas, and both spiritual and material harmony through the grace of the Divine Mother.",
    items_to_bring: [
      "Kumkum, turmeric, and fresh flowers",
      "Fruits and naivedyam",
      "Devi photo or vigraham if performed at home",
      "Any additional puja samagri advised for Chandi Path observance",
    ],
    whats_included: [
      "Sankalpam and preparatory prayers",
      "Nyasa, kavacha, argala, and keelaka where observed",
      "Complete Devi Saptashati / Chandi Path recitation",
      "Devi upacharas, concluding prayers, and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-3",
    category_id: "cat-2",
    name: "SUNDARAKANDA PATH (PARAYANAM)",
    slug: "sundarakanda-path-parayanam",
    short_description:
      "A devotional recitation of Sundara Kanda invoking Hanuman’s courage, protection, clarity, and grace.",
    full_description:
      "Sundarakanda Path, or Sundara Kanda Parayanam, is the devotional recitation of the Sundara Kanda, a beautiful and powerful chapter of the Ramayana centered on Sri Hanuman's heroic journey to Lanka. It is called Sundara because it beautifully reveals pure bhakti joined with fearless action. In this sacred episode, Hanuman discovers Sita Mata, gives her hope, and delivers Sri Rama's message. Every verse radiates courage, clarity, devotion, and grace, making this parayanam especially beloved during difficult periods, major undertakings, and devotional observances.",
    significance:
      "Devotees associate Sundarakanda Path with the removal of obstacles and fear, mental strength and focus, protection from negativity, Saturn dosha relief, and the blessings of Hanuman and Sri Rama.",
    items_to_bring: [
      "Hanuman or Sri Rama photo or vigraham",
      "Flowers, betel leaves, and fruits",
      "Naivedyam and ghee lamp",
      "Any additional devotional items advised by Panditji",
    ],
    whats_included: [
      "Sankalpam",
      "Complete or guided Sundarakanda recitation",
      "Hanuman and Sri Rama prayers",
      "Mangala harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 150,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-4",
    category_id: "cat-3",
    name: "ANNA SHRADHAM (ANCESTRAL PRAYERS)",
    slug: "anna-shraddham",
    short_description:
      "A Vaidika Pitru-karma performed with sacred discipline for ancestral satisfaction, blessings, and lineage continuity.",
    full_description:
      "Anna Shraddham is a Vaidika Pitru-karma enjoined in the Dharmashastras, Grihya Sutras, and Smriti texts for the propitiation of the Pitrs and the discharge of Pitru-rina, the ancestral obligation incumbent upon the householder. Classified as a nitya-naimittika karma, it is performed with sankalpam, pinda-pradana, anna-nivedana, tilodaka-dana, and dakshina, in conformity with scriptural injunction and inherited ritual discipline. The shastras affirm that through proper Shraddha, the Pitrs attain tripti and shanti, bestow their anugraha upon descendants, and ensure continuity of lineage, prosperity, and spiritual stability, thereby sustaining rta, the cosmic order upheld by dharma. The fruit of Anna Shraddham arises not from external elaboration, but from precision of rite, purity of intent, and unwavering adherence to sacred law.",
    significance:
      "This sacred observance is performed for Pitru tripti, blessings of the ancestors, increase in longevity, continuity of lineage, prosperity, and spiritual steadiness within the household.",
    items_to_bring: [
      "Cooked offering materials as advised by Panditji",
      "Sesame seeds, darbha, and tilodaka materials",
      "Vastra, dakshina, and ritual vessels",
      "Banana leaves, fruits, and betel leaves",
    ],
    whats_included: [
      "Sankalpam and full Shraddha vidhi guidance",
      "Pinda-pradana and anna-nivedana",
      "Tilodaka-dana and Pitru-karya observance",
      "Concluding blessings in accordance with family tradition",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-5",
    category_id: "cat-3",
    name: "HIRANYA SHRADHAM (ANCESTORAL OFFERING)",
    slug: "hiranya-shraddham",
    short_description:
      "A sacred Vaidika ancestral observance performed through sankalpam, mantra, and dana for Pitru grace and lineage protection.",
    full_description:
      "Human birth is not an isolated event; our body, lineage, values, and the very opportunity to live this life arise from the blessings of our ancestors, and therefore the scriptures declare that honoring them is a sacred duty. The Vedic teaching 'Matridevo bhava, Pitridevo bhava' and the doctrine of the three debts affirm that Pitru-rina is discharged only through Shraddha and sincere remembrance. Recognizing this truth, the shastras approve Hiranya Shraddham as a complete and valid form of ancestral observance, fulfilled through sincere sankalpam, remembrance of the lineage, focused mantra recitation, and dakshina or charitable offerings made in the name of the Pitrs. When ancestors are remembered with reverence and devotion, harmony is maintained within the family, health and lineage continuity are protected, obstacles are reduced, and unseen blessings begin to flow. This observance is not about dwelling on death, but about honoring the source of our life and remaining connected to our roots through gratitude, humility, responsibility, and devotion.",
    significance:
      "Hiranya Shraddham is performed for Pitru satisfaction, family harmony, removal of obstacles, lineage continuity, and the sustaining blessings of the ancestors upon present and future generations.",
    items_to_bring: [
      "Sesame seeds and darbha",
      "Dakshina or hiranya offering",
      "Fruits, betel leaves, and simple naivedyam",
      "Any required ritual items as advised by Panditji",
    ],
    whats_included: [
      "Sankalpam with lineage remembrance",
      "Pitru mantra recitation and observance guidance",
      "Hiranya-based offering and dana procedure",
      "Closing prayers and blessings in accordance with family tradition",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-6",
    category_id: "cat-4",
    name: "SHIVA PARVATI KALYANAM (CELESTIAL WEDDING CEREMONY OF SHIVA AND PARVATI)",
    slug: "shiva-parvati-kalyanam",
    short_description:
      "A divine kalyanam celebrating the sacred union of Shiva and Parvati as love, balance, devotion, and cosmic harmony.",
    full_description:
      "According to the Puranas, the love of Shiva and Parvati unfolds through grief, longing, and unshakable devotion. After Sati's self-immolation, Shiva withdraws into fierce detachment, and creation itself is thrown out of balance. Parvati, carrying the soul-memory of Sati, approaches Shiva not with impatience but with quiet perseverance, embracing tapasya, faith, and compassion that understands his pain rather than trying to erase it. When Shiva finally accepts her, their marriage restores harmony to creation, proving that supreme detachment and supreme love are not contradictions but complements. Celebrated on Mount Kailasa, with Brahma performing the sacred rites and Vishnu offering blessings, this divine union establishes cosmic balance and leads to the birth of Ganesha and Kartikeya. Shiva Parvati Kalyanam teaches that true partnership rests upon equality, patience, and shared purpose, and that spiritual awakening is fulfilled not by rejecting life, but by embracing it with responsibility, compassion, and inner steadiness.",
    significance:
      "This kalyanam is performed for marital harmony, family wellbeing, shared purpose in household life, and the blessings of Shiva and Parvati upon relationships, dharma, and inner balance.",
    items_to_bring: [
      "Flowers, garlands, fruits, and coconuts",
      "Naivedyam offerings and mangalya items as advised",
      "New vastram for deities if desired",
      "Any additional kalyana samagri recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and full kalyana vidhi",
      "Complete Shiva Parvati Kalyanam procedure",
      "Mangalya, talambralu, and auspicious ceremonial observances",
      "Harati, blessings, and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-7",
    category_id: "cat-5",
    name: "MAHANYASA PURVAKA EKADASA RUDRABHISHEKAM",
    slug: "mahanyasa-purvaka-ekadasa-rudrabhishekam",
    short_description:
      "A powerful Shaiva ritual combining Mahanyasa with 11-fold Rudrabhishekam and full Sri Rudram chanting.",
    full_description:
      "Mahanyasa Purvaka Ekadasa Rudrabhishekam is one of the most powerful and complete Shaiva rituals, combining Mahanyasa with Ekadasa, or 11-fold, Rudrabhishekam to invoke Lord Shiva in all His cosmic forms. Mahanyasa is an elaborate Vedic purification and consecration of the body using mantras from Sri Rudram, preparing both the priest and the ritual space by aligning body, mind, and prana with Rudra-tattva before worship begins. Ekadasa Rudrabhishekam means the Shiva Linga is worshipped with 11 complete Rudrabhishekams, representing the 11 Rudras, the 11 senses, and the 11 forms of cosmic energy. Each abhishekam is accompanied by full chanting of Namakam and Chamakam. The ritual includes sankalpam, Mahanyasa, Kara-Anga Nyasa, abhishekams with sacred substances such as water, milk, curd, honey, ghee, sugarcane juice, coconut water, panchamrita, and special herbal waters, followed by arati and prasada vitarana.",
    significance:
      "This sacred ritual is believed to remove negative karma and deep-rooted obstacles, bring mental peace and emotional healing, support health and longevity, promote family harmony, and grant Shiva anugraha for both material and spiritual upliftment.",
    items_to_bring: [
      "Flowers, bilva leaves, and naivedyam offerings",
      "Milk, curd, honey, ghee, and fruits",
      "Panchamrita and special abhisheka dravyas as advised",
      "Any additional Shiva puja samagri recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and Mahanyasa purvaka purification",
      "Kara-Anga Nyasa and Sri Rudram chanting",
      "11-fold Rudrabhishekam with sacred substances",
      "Harati, prasada vitarana, and concluding blessings",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 210,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-8",
    category_id: "cat-4",
    name: "SRI SEETA RAMA KALYANAM (CELESTIAL WEDDING CEREMONY OF SEETA RAMA)",
    slug: "sri-seeta-rama-kalyanam",
    short_description:
      "A sacred kalyanam celebrating Seeta and Rama as the ideal union of dharma, devotion, virtue, and shared responsibility.",
    full_description:
      "Seeta Rama Kalyanam, the divine wedding of Sree Seeta and Lord Sree Rama, holds deep spiritual and human significance as it presents the ideal model of marriage rooted in righteousness, mutual respect, and unwavering commitment. This sacred union teaches that marriage is not merely a social bond but a lifelong spiritual journey in which two souls walk together on the path of dharma. Rama represents truth, duty, and moral discipline, while Sita stands for purity, inner strength, patience, and devotion; together they show how harmony is achieved through balance, sacrifice, and understanding. Their wedding reminds humanity that love must be guided by values, not desire, and strength must be guided by humility. Sita is revered as sahadharmacharini, Rama's equal partner in dharma, and this divine kalyanam continues to inspire generations toward virtue, faith, shared responsibility, and auspicious family life.",
    significance:
      "This kalyanam is performed for marital harmony, auspiciousness, prosperity, spiritual fulfillment, and the blessings of Seeta and Rama upon family life guided by dharma.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Garlands, mangalya items, and kalyana samagri as advised",
      "New vastram for the deities if desired",
      "Any additional offerings recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and complete kalyana preparations",
      "Full Sri Seeta Rama Kalyanam procedure",
      "Mangala harati, blessings, and prasadam",
      "Auspicious family blessings in the spirit of dharma",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-9",
    category_id: "cat-4",
    name: "SRINIVASA KALYANAM (CELESTIAL WEDDING CEREMONY)",
    slug: "srinivasa-kalyanam",
    short_description:
      "A sacred kalyanam celebrating Lord Srinivasa and Goddess Padmavati as the divine union of grace, prosperity, family harmony, and dharma.",
    full_description:
      "Srinivasa Kalyanam, the celestial wedding of Lord Srinivasa (Venkateswara) with Goddess Padmavati (Alamelumanga), signifies the sacred union of compassion and prosperity, where the Lord's boundless grace is eternally accompanied by Lakshmi's abundance, assuring devotees that sincere prayers are never unanswered. This divine marriage marks Vishnu's full commitment to earthly life in Kali Yuga, showing that He willingly embraces human responsibilities, debts, and duties so that He may walk alongside humanity in its struggles. It also establishes Grihastha Dharma as a holy and complete spiritual path in which family life, harmony, responsibility, and devotion coexist. After the wedding, Alamelumanga's eternal residence on the Lord's chest symbolizes her mediating presence that softens the Lord's judgments with mercy, making Tirumala revered as Kaliyuga Vaikuntha. For devotees, witnessing or sponsoring this kalyanam is believed to bestow marital harmony, suitable alliances, family stability, inner peace, and the blessings of Lord Srinivasa and Goddess Padmavati upon household life.",
    significance:
      "This kalyanam is performed for marital harmony, suitable alliances, family stability, prosperity, inner peace, and the grace of Srinivasa and Padmavati in Kali Yuga.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Garlands, mangalya items, and kalyana samagri as advised",
      "New vastram offerings if desired",
      "Any additional puja materials recommended by Panditji",
    ],
    whats_included: [
      "Priest-brought moorthis of Lord Srinivasa and Goddess Padmavati-Alamelumanga",
      "Sankalpam and complete kalyana preparations",
      "Full Srinivasa Kalyanam wedding ritual as per Vedic tradition",
      "Mangala harati, blessings, and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 3,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-10",
    category_id: "cat-1",
    name: "PUMSAVANAM",
    slug: "pumsavanam",
    short_description:
      "Mother-womb protection puja performed in the Vedic way during pregnancy.",
    full_description:
      "Pumsavanam is a sacred Vedic samskara performed for the wellbeing of the expectant mother and the protection of the child in the womb. This ceremony invokes divine blessings for healthy development, peace in the household, and spiritual protection during pregnancy.",
    significance:
      "This samskara is traditionally performed for maternal wellbeing, fetal protection, peaceful pregnancy, and the blessings of dharma upon the growing family.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Saree or vastram offerings if desired",
      "Basic puja samagri as advised by Panditji",
      "Any additional family-specific offerings recommended in advance",
    ],
    whats_included: [
      "Sankalpam and complete Vedic puja procedure",
      "Mantra recitation for mother and child wellbeing",
      "Blessings for peaceful pregnancy and family harmony",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 4,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-11",
    category_id: "cat-1",
    name: "SEEMANTAM",
    slug: "seemantam",
    short_description:
      "Traditional Vedic baby shower puja, including the sacred parting of the wife's hair.",
    full_description:
      "Seemantam is a cherished Vedic samskara performed during pregnancy as a blessing ceremony for the expectant mother and child. Often understood as a sacred baby shower in the Vedic tradition, it includes auspicious rituals, blessings from elders, and prayers for safe delivery, joyful motherhood, and family wellbeing.",
    significance:
      "This ceremony is performed for the protection of mother and child, emotional wellbeing, safe childbirth, and auspicious blessings for the growing family.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Saree, bangles, and customary family offerings if desired",
      "Turmeric, kumkum, and puja samagri as advised",
      "Any special Seemantam items recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and Vedic baby shower rituals",
      "Traditional Seemantam observances including hair-parting blessing",
      "Family blessings and auspicious mantra recitation",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 5,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-12",
    category_id: "cat-1",
    name: "JATAKARMA",
    slug: "jatakarma",
    short_description:
      "The first samskara performed after a baby's birth in the Vedic tradition.",
    full_description:
      "Jatakarma is the first samskara after the birth of a child. This sacred rite welcomes the newborn into life with blessings, prayers, and traditional observances for health, purity, protection, and spiritual wellbeing.",
    significance:
      "This first-life samskara is performed to bless the newborn, welcome the child into dharmic family life, and invoke divine protection and auspicious beginnings.",
    items_to_bring: [
      "Flowers, fruits, and naivedyam offerings",
      "Items for the newborn as advised by family custom",
      "Basic puja samagri recommended by Panditji",
      "Any additional offerings desired by the family",
    ],
    whats_included: [
      "Sankalpam and newborn blessing rituals",
      "Traditional Jatakarma samskara observances",
      "Prayers for health, longevity, and auspicious life",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 75,
    location_type: "both",
    is_active: true,
    sort_order: 6,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-13",
    category_id: "cat-1",
    name: "ANNAPRASANA",
    slug: "annaprasana",
    short_description:
      "Rice feeding ceremony marking the baby's first time receiving solid food, usually from the sixth month.",
    full_description:
      "Annaprasana is the traditional first rice feeding ceremony performed for a baby, typically from the sixth month onward. This joyful samskara marks the child's first ceremonial intake of food and seeks blessings for nourishment, health, growth, and a prosperous life ahead.",
    significance:
      "This ceremony celebrates nourishment, healthy growth, family joy, and the child's auspicious progression through the early samskaras of life.",
    items_to_bring: [
      "Cooked rice or ceremonial first-food items as advised",
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Baby clothing or family offerings if desired",
      "Additional puja samagri recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and complete Annaprasana ritual",
      "Blessings for nourishment, health, and growth",
      "Ceremonial first feeding observance",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 7,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-14",
    category_id: "cat-1",
    name: "UPANAYANAM / JENEAU",
    slug: "upanayanam-jeneau",
    short_description:
      "Sacred thread ceremony performed as a major Vedic samskara and spiritual initiation.",
    full_description:
      "Upanayanam, also known as the sacred thread ceremony, is an important Vedic samskara marking spiritual initiation and disciplined entry into study, responsibility, and dharmic life. It is traditionally performed with mantra, guidance, and blessings for a life rooted in wisdom, discipline, and sacred duty.",
    significance:
      "This samskara signifies spiritual initiation, responsibility, disciplined learning, and the beginning of a deeper life of dharma and Vedic observance.",
    items_to_bring: [
      "Vastram and sacred thread materials as advised",
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Family-specific samagri for the ceremony",
      "Additional puja materials recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and full Upanayanam procedure",
      "Sacred thread ceremony with Vedic mantra recitation",
      "Blessings for learning, discipline, and dharma",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 8,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-15",
    category_id: "cat-4",
    name: "VIVAHAM / WEDDING",
    slug: "vivaham-wedding",
    short_description:
      "A sacred marriage ceremony joining two individuals in the shared pursuit of dharma, artha, kama, and moksha.",
    full_description:
      "Vivaham, or wedding, is the sacred samskara through which two individuals, understood as embodied eternal souls, are joined in marriage for the shared pursuit of the four aims of life: dharma, artha, kama, and moksha. In the Vedic view, marriage is not merely a social contract but a profound spiritual partnership rooted in duty, companionship, harmony, and mutual upliftment.",
    significance:
      "This ceremony sanctifies marriage as a dharmic partnership and blesses the couple for harmony, prosperity, shared purpose, and spiritual growth.",
    items_to_bring: [
      "Garlands, mangalya items, and wedding samagri as advised",
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Vastram for bride and groom and deity offerings as desired",
      "Any family-specific wedding items recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and full Vedic marriage procedure",
      "Core wedding rites for the sacred union of the couple",
      "Blessings for dharma, prosperity, and family life",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 240,
    location_type: "both",
    is_active: true,
    sort_order: 4,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-16",
    category_id: "cat-1",
    name: "KESHAKHANDANA / MUNDAN",
    slug: "keshakhandana-mundan",
    short_description:
      "First head-shaving ceremony for a child, also known as the hair tonsuring ceremony.",
    full_description:
      "Keshakhandana, also known as Mundan, is the traditional first head-shaving ceremony performed after a child's birth. This samskara is observed as a rite of purification and blessing, and is traditionally associated with auspicious beginnings, spiritual cleansing, and healthy growth.",
    significance:
      "This samskara is performed for purification, auspicious beginnings, and blessings upon the child's growth and wellbeing.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Child's clothing and personal items as needed",
      "Traditional family offerings if desired",
      "Additional puja samagri as advised by Panditji",
    ],
    whats_included: [
      "Sankalpam and Mundan/Keshakhandana rituals",
      "Blessings for purification and healthy growth",
      "Traditional samskara observances",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 9,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-17",
    category_id: "cat-1",
    name: "AKSHARABHYASAM / VIDYARAMBHAM",
    slug: "aksharabhyasam-vidyarambham",
    short_description:
      "A sacred learning-initiation ceremony invoking Goddess Saraswati before school and education begin.",
    full_description:
      "Aksharabhyasam, also known as Vidyarambham, is the traditional ceremony of initiating a child into learning. Performed before starting school and education, this samskara invokes knowledge, wisdom, and the blessings of Goddess Saraswati so that the child's path of study begins in an auspicious and spiritually grounded way.",
    significance:
      "This ceremony invokes learning, wisdom, clarity, and the blessings of Goddess Saraswati for the child's educational journey.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Rice tray, slate, notebook, or writing items as advised",
      "Offerings for Goddess Saraswati if desired",
      "Additional puja materials recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and Saraswati invocation",
      "Traditional Aksharabhyasam / Vidyarambham procedure",
      "Blessings for knowledge, focus, and auspicious learning",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 75,
    location_type: "both",
    is_active: true,
    sort_order: 10,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-18",
    category_id: "cat-5",
    name: "MAHA LINGARCHANA",
    slug: "maha-lingarchana",
    short_description:
      "A sacred Shiva archana performed with deep reverence to the Lingam through traditional Vedic worship.",
    full_description:
      "Maha Lingarchana is a sacred Shaiva worship service centered on the Shiva Lingam and performed with mantra, archana, and traditional ritual observances. It is offered for divine grace, inner purification, peace, and the blessings of Lord Shiva upon the devotee and family.",
    significance:
      "This service is performed to invoke Shiva anugraha, remove negativity, support spiritual steadiness, and bring auspiciousness and protection.",
    items_to_bring: [
      "Flowers, bilva leaves, fruits, and naivedyam offerings",
      "Milk, water, and abhisheka items if advised",
      "Basic Shiva puja samagri as recommended by Panditji",
      "Any family-specific offerings desired for the archana",
    ],
    whats_included: [
      "Sankalpam and Shiva archana procedure",
      "Traditional mantra recitation and offerings",
      "Blessings for peace, purification, and divine grace",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-19",
    category_id: "cat-1",
    name: "CHANDI HOMAM",
    slug: "chandi-homam",
    short_description:
      "A powerful homam invoking the Divine Mother for protection, courage, victory, and removal of negativity.",
    full_description:
      "Chandi Homam is a profound fire ritual dedicated to the Divine Mother in her fierce and compassionate form. It is performed for protection, removal of obstacles, victory over negativity, courage, and the blessings of Devi for spiritual and material wellbeing.",
    significance:
      "This homam is traditionally observed for dosha relief, strength, protection from unseen negativity, and the grace of the Divine Mother in difficult times.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Homam dravyas as advised by Panditji",
      "Kumkum, turmeric, and Devi offerings",
      "Any additional samagri recommended for Chandi Homam",
    ],
    whats_included: [
      "Sankalpam and homa setup",
      "Devi mantra recitation and fire offerings",
      "Complete Chandi Homam observance",
      "Harati, blessings, and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 11,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-20",
    category_id: "cat-1",
    name: "SURYA YANTRA NAMASKARA PUJA",
    slug: "surya-yantra-namaskara-puja",
    short_description:
      "A Surya-focused puja with yantra worship and namaskara for vitality, clarity, and auspicious solar blessings.",
    full_description:
      "Surya Yantra Namaskara Puja is a sacred worship service offered to Surya Bhagavan with reverence to the yantra, mantra, and traditional observances. It is performed for energy, health, clarity, confidence, and favorable solar blessings in life.",
    significance:
      "This puja is associated with vitality, mental clarity, discipline, health, and relief from certain planetary afflictions connected to Surya.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Red or orange cloth and Surya offerings if advised",
      "Yantra-related puja samagri as recommended",
      "Any additional family offerings desired",
    ],
    whats_included: [
      "Sankalpam and Surya yantra worship",
      "Traditional mantra recitation and namaskara observances",
      "Blessings for vitality, clarity, and auspiciousness",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 12,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-21",
    category_id: "cat-5",
    name: "LAGHUNYASA EKAVAARA RUDRABHISHEKAM",
    slug: "laghunyasa-ekavaara-rudrabhishekam",
    short_description:
      "A sacred Rudrabhishekam performed with Laghunyasa and Shiva mantra worship for peace and purification.",
    full_description:
      "Laghunyasa Ekavaara Rudrabhishekam is a traditional Shiva worship service that combines Laghunyasa with a focused Rudrabhishekam observance. It is performed for peace, spiritual cleansing, family wellbeing, and the blessings of Lord Shiva.",
    significance:
      "This ritual is associated with removal of negativity, inner steadiness, health, and Shiva anugraha for household and spiritual life.",
    items_to_bring: [
      "Flowers, bilva leaves, fruits, and naivedyam offerings",
      "Milk, water, and abhisheka dravyas as advised",
      "Basic Shiva puja materials recommended by Panditji",
      "Additional offerings if desired",
    ],
    whats_included: [
      "Sankalpam and Laghunyasa procedure",
      "Rudrabhishekam with mantra recitation",
      "Blessings for purification, peace, and grace",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 3,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-22",
    category_id: "cat-1",
    name: "NAMAKARAN (NAMING CEREMONY)",
    slug: "namakaran-naming-ceremony",
    short_description:
      "Traditional naming ceremony performed as a sacred samskara for the newborn child.",
    full_description:
      "Namakaran is the sacred naming ceremony performed for a newborn as one of the important samskaras of early life. The ritual blesses the child with identity, auspicious beginnings, and loving entry into family and dharmic tradition.",
    significance:
      "This ceremony invokes blessings for the child’s health, growth, identity, and auspicious future within the family lineage.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Baby clothing and family offerings if desired",
      "Basic puja samagri as advised by Panditji",
      "Any additional samskara items recommended in advance",
    ],
    whats_included: [
      "Sankalpam and complete Namakaran observance",
      "Blessings for the newborn and family",
      "Traditional naming ritual procedure",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 75,
    location_type: "both",
    is_active: true,
    sort_order: 13,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-23",
    category_id: "cat-2",
    name: "SATYANARAYANA KATHA",
    slug: "satyanarayana-katha",
    short_description:
      "A sacred Satyanarayana observance centered on katha recitation, devotion, and blessings for family wellbeing.",
    full_description:
      "Satyanarayana Katha is a revered devotional observance centered on Lord Satyanarayana and the sacred recitation of the katha. It is performed for gratitude, auspiciousness, prosperity, family wellbeing, and the blessings of Vishnu in household life.",
    significance:
      "This katha is associated with peace, prosperity, fulfillment of sincere prayers, and harmonious family life through devotion to Lord Satyanarayana.",
    items_to_bring: [
      "Flowers, fruits, coconuts, bananas, and naivedyam offerings",
      "Puja items for Lord Satyanarayana as advised",
      "Prasadam ingredients if being prepared at home",
      "Any additional family offerings desired",
    ],
    whats_included: [
      "Sankalpam and Satyanarayana puja",
      "Katha recitation and devotional observances",
      "Blessings for prosperity and family wellbeing",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-24",
    category_id: "cat-4",
    name: "SNATAKAM / KAASIYATRA",
    slug: "snatakam-kaasiyattra",
    short_description:
      "A traditional pre-wedding ritual observed before marriage as part of the broader Vedic wedding sequence.",
    full_description:
      "Snatakam and Kaasiyatra are traditional pre-wedding observances performed before the main marriage ceremony. They are part of the larger Vedic wedding sequence and symbolize transition, preparation, responsibility, and the sacred movement into married life.",
    significance:
      "These rituals are performed to sanctify the groom’s transition into marriage and uphold the auspicious and traditional order of the wedding process.",
    items_to_bring: [
      "Wedding-related samagri as advised by Panditji",
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Vastram and ceremonial family items if desired",
      "Any additional pre-wedding ritual materials recommended",
    ],
    whats_included: [
      "Sankalpam and pre-wedding ritual preparations",
      "Traditional Snatakam and Kaasiyatra observances",
      "Blessings for auspicious transition into marriage",
      "Harati and concluding blessings",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 5,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-25",
    category_id: "cat-2",
    name: "SATYANARAYANA VRATAM",
    slug: "satyanarayana-vratam",
    short_description:
      "A sacred vratam dedicated to Lord Satyanarayana for peace, prosperity, gratitude, and divine blessings.",
    full_description:
      "Satyanarayana Vratam is a sacred devotional observance performed in reverence to Lord Satyanarayana. It is widely observed for family peace, prosperity, thanksgiving, fulfillment of vows, and the auspicious grace of Vishnu in household life.",
    significance:
      "This vratam is associated with prosperity, protection, gratitude, peaceful family life, and the blessings of Lord Satyanarayana.",
    items_to_bring: [
      "Flowers, fruits, coconuts, bananas, and naivedyam offerings",
      "Puja samagri for Lord Satyanarayana as advised",
      "Prasadam ingredients when prepared by the family",
      "Additional offerings if desired",
    ],
    whats_included: [
      "Sankalpam and Satyanarayana puja procedure",
      "Traditional vratam observance and prayers",
      "Blessings for peace, prosperity, and gratitude",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 3,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-26",
    category_id: "cat-1",
    name: "BALARISTA DOSHA NIVARANA",
    slug: "balarista-dosha-nivarana",
    short_description:
      "A protective puja performed for relief from Balarishta-related afflictions and the wellbeing of the child.",
    full_description:
      "Balarista Dosha Nivarana is a traditional remedial puja performed for the wellbeing, protection, and stability of a child when certain astrological concerns are present. It is observed with faith and prayer for divine protection, health, and relief from unfavorable influences.",
    significance:
      "This puja is performed to seek protection for the child, reduce astrological afflictions, and invoke blessings for healthy growth and wellbeing.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Child-related family offerings if desired",
      "Graha shanti items as advised by Panditji",
      "Any additional remedial samagri recommended",
    ],
    whats_included: [
      "Sankalpam and dosha nivarana puja",
      "Traditional mantra recitation and remedial worship",
      "Blessings for child protection and wellbeing",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 14,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-27",
    category_id: "cat-1",
    name: "KUJA DOSHA NIVARANA",
    slug: "kuja-dosha-nivarana",
    short_description:
      "A remedial puja performed for relief from Kuja dosha and for harmony, stability, and auspicious progress.",
    full_description:
      "Kuja Dosha Nivarana is a traditional remedial puja performed to seek relief from afflictions associated with Kuja (Mars). It is often observed for harmony, marriage-related concerns, peace, stability, and removal of obstacles associated with planetary imbalance.",
    significance:
      "This puja is associated with graha shanti, harmony, courage, stability, and reduction of obstacles linked to Kuja dosha.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Graha-related puja samagri as advised",
      "Red cloth or special offerings if recommended",
      "Any additional family offerings desired",
    ],
    whats_included: [
      "Sankalpam and dosha nivarana worship",
      "Traditional graha shanti mantra recitation",
      "Blessings for stability, peace, and auspiciousness",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 15,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-28",
    category_id: "cat-1",
    name: "NAKSHATRA SHANTHI HOMA",
    slug: "nakshatra-shanthi-homa",
    short_description:
      "A nakshatra-based shanthi homa performed for peace, remedial blessings, and astrological balance.",
    full_description:
      "Nakshatra Shanthi Homa is a sacred fire ritual performed in relation to a specific birth star or astrological need. It is observed for peace, remedial blessing, wellbeing, and balance when family or individual circumstances call for nakshatra-based worship.",
    significance:
      "This homa is associated with planetary and star-based peace, family wellbeing, and spiritual support during sensitive astrological periods.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Homa dravyas and graha shanti items as advised",
      "Birth star details for sankalpam",
      "Any additional samagri recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and nakshatra-specific worship",
      "Traditional homa procedure and fire offerings",
      "Blessings for peace, balance, and wellbeing",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 16,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-29",
    category_id: "cat-1",
    name: "BHOOMI POOJA / GROUND BREAKING",
    slug: "bhoomi-pooja-ground-breaking",
    short_description:
      "A sacred ground-breaking and land blessing ceremony performed before beginning construction or major site work.",
    full_description:
      "Bhoomi Pooja is a traditional Hindu ritual performed before construction, land development, or the beginning of major work on a property. It is offered with reverence to the earth and the divine forces governing the space so that the project begins with peace, stability, and auspicious blessings.",
    significance:
      "This puja is performed for land blessing, removal of obstacles, vastu harmony, and auspicious beginnings before construction or site work.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Bricks, soil, or construction-related items if advised",
      "Turmeric, kumkum, and land puja samagri as recommended",
      "Any additional site-specific offerings desired",
    ],
    whats_included: [
      "Sankalpam and Bhoomi Pooja procedure",
      "Traditional earth-blessing and auspicious rituals",
      "Prayers for stability, safety, and successful beginnings",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "outside_temple",
    is_active: true,
    sort_order: 17,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-30",
    category_id: "cat-2",
    name: "LAKSHA VARTI VRATAM",
    slug: "laksha-varti-vratam",
    short_description:
      "A sacred lamp-centered vratam observed with devotion, light offerings, and prayers for blessings and fulfillment.",
    full_description:
      "Laksha Varti Vratam is a devotional observance centered on the offering of lamps and sacred worship performed with faith, vrata discipline, and prayer. It is observed for auspicious blessings, devotion, fulfillment, and inner light in family and spiritual life.",
    significance:
      "This vratam is associated with devotion, grace, auspiciousness, and the symbolic triumph of sacred light over difficulty and darkness.",
    items_to_bring: [
      "Deepam materials, cotton wicks, and oil or ghee as advised",
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Vratam-specific samagri as recommended by Panditji",
      "Any additional devotional offerings desired",
    ],
    whats_included: [
      "Sankalpam and vratam observance",
      "Lamp worship and devotional mantra recitation",
      "Blessings for fulfillment, light, and auspiciousness",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 4,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-31",
    category_id: "cat-1",
    name: "SAHASRA CHANDRA DARSHANAM",
    slug: "sahasra-chandra-darshanam",
    short_description:
      "A milestone ceremony honoring the sacred completion of one thousand full moon darshans in life.",
    full_description:
      "Sahasra Chandra Darshanam is a revered milestone observance traditionally associated with the blessing of witnessing one thousand full moons in a lifetime. It is celebrated with gratitude, family reverence, and prayers for health, peace, longevity, and fulfillment.",
    significance:
      "This sacred milestone ceremony honors longevity, family continuity, gratitude, and the blessings of a life ripened through dharma and time.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Vastram and family offerings if desired",
      "Milestone celebration samagri as advised",
      "Any additional blessings items recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and milestone puja observance",
      "Blessings for health, peace, and longevity",
      "Traditional family-centered ceremonial procedure",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 18,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-32",
    category_id: "cat-1",
    name: "BHEEMARATHA SHANTI",
    slug: "bheemaratha-shanti",
    short_description:
      "A traditional longevity and peace ceremony observed at an important life milestone for health and family blessings.",
    full_description:
      "Bheemaratha Shanti is a traditional milestone ceremony performed for peace, health, longevity, and auspicious family blessings at a significant stage of life. It is observed with gratitude, prayer, and family participation to mark the journey of life with reverence and dharmic meaning.",
    significance:
      "This ceremony is associated with longevity, family harmony, wellbeing, and peaceful continuation through important life milestones.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Vastram and family celebration samagri if desired",
      "Traditional milestone puja items as advised",
      "Any additional offerings recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and Bheemaratha Shanti observance",
      "Blessings for health, peace, and longevity",
      "Traditional milestone ritual procedure",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 19,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-33",
    category_id: "cat-1",
    name: "PUNYAHAVACHANAM",
    slug: "punyahavachanam",
    short_description:
      "A purification and sanctification ceremony performed to bless a person, family, home, or occasion in the Vedic way.",
    full_description:
      "Punyahavachanam is a traditional Vedic purification and sanctification ceremony performed to invoke purity, auspiciousness, and divine blessing before or alongside important family and ritual occasions. It is widely observed for homes, ceremonies, and transitions that call for spiritual cleansing and sacred commencement.",
    significance:
      "This ceremony is performed for purification, auspicious beginnings, spiritual cleansing, and divine blessing upon important occasions.",
    items_to_bring: [
      "Kalasham, mango leaves, coconut, and flowers",
      "Fruits, naivedyam, turmeric, and kumkum",
      "Basic puja samagri as advised by Panditji",
      "Any additional family-specific offerings desired",
    ],
    whats_included: [
      "Sankalpam and purification procedure",
      "Kalasha and sanctification observances",
      "Blessings for purity, peace, and auspiciousness",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 75,
    location_type: "both",
    is_active: true,
    sort_order: 20,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-34",
    category_id: "cat-1",
    name: "SHASTIPOORTI",
    slug: "shastipoorti",
    short_description:
      "A traditional 60th-year milestone ceremony observed for longevity, peace, gratitude, and family blessings.",
    full_description:
      "Shastipoorti is a sacred milestone observance traditionally celebrated around the completion of sixty years. It is performed with prayer, gratitude, family participation, and Vedic blessings for health, peace, continued companionship, and auspicious life ahead.",
    significance:
      "This ceremony honors longevity, family life, gratitude, and the blessings of a meaningful life journey rooted in dharma.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Vastram and family celebration items if desired",
      "Milestone ceremony samagri as advised",
      "Additional offerings recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and Shastipoorti observance",
      "Blessings for longevity, peace, and family wellbeing",
      "Traditional milestone ceremonial procedure",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 21,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-35",
    category_id: "cat-1",
    name: "GRUHAPRAVESHAM PUJA",
    slug: "gruhapravesham-puja",
    short_description:
      "A traditional housewarming and first-entry puja performed for a new home in the Vedic way.",
    full_description:
      "Gruhapravesham Puja is the sacred housewarming ceremony performed before first entry into a new home. It is observed for purification, vastu harmony, auspicious beginnings, family wellbeing, and the blessings of divine presence within the household.",
    significance:
      "This puja is associated with home purification, peaceful living, vastu balance, prosperity, and auspicious first entry into the new house.",
    items_to_bring: [
      "Milk, rice, coconuts, fruits, flowers, and naivedyam offerings",
      "Kalasham and housewarming puja items as advised",
      "Turmeric, kumkum, mango leaves, and lamps",
      "Any additional home-specific offerings desired",
    ],
    whats_included: [
      "Sankalpam and Gruhapravesham procedure",
      "Purification and auspicious first-entry observances",
      "Blessings for peace, prosperity, and household wellbeing",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "outside_temple",
    is_active: true,
    sort_order: 22,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-36",
    category_id: "cat-1",
    name: "GANAPATHI PUJA",
    slug: "ganapathi-puja",
    short_description:
      "Traditional worship of Lord Ganesha for auspicious beginnings, obstacle removal, and family blessings.",
    full_description:
      "Ganapathi Puja is a sacred worship service offered to Lord Ganesha, the remover of obstacles and the deity invoked before auspicious beginnings. It is performed for peace, clarity, success, and blessings before important events, new undertakings, or family milestones.",
    significance:
      "This puja is associated with obstacle removal, auspicious beginnings, clarity, success, and the blessings of Lord Ganesha in all undertakings.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Durva grass and Ganesha offerings if advised",
      "Turmeric, kumkum, and lamps",
      "Any additional puja samagri recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and Ganapathi Puja procedure",
      "Traditional mantra recitation and offerings",
      "Blessings for success, peace, and obstacle removal",
      "Harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 75,
    location_type: "both",
    is_active: true,
    sort_order: 23,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
];

export const sampleEvents: Event[] = [
  {
    id: "evt-1",
    title: "Ugadi Celebrations 2026",
    description:
      "Telugu and Kannada New Year celebrations with special poojas, cultural programs, and festive feast. Join us for Panchangam Sravanam and Ugadi Pachadi distribution.",
    event_type: "festival",
    start_date: "2026-03-29",
    end_date: "2026-03-29",
    start_time: "09:00",
    end_time: "14:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 45,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-2",
    title: "Sri Rama Navami",
    description:
      "Celebration of Lord Rama's birth with Sita Rama Kalyanotsavam, Abhishekam, and special cultural programs throughout the day.",
    event_type: "festival",
    start_date: "2026-04-07",
    end_date: "2026-04-07",
    start_time: "08:00",
    end_time: "20:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 78,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-3",
    title: "Weekly Bhajan Sandhya",
    description:
      "Join us every Saturday evening for devotional bhajans and kirtans. All are welcome to participate and immerse in the divine melodies.",
    event_type: "regular_pooja",
    start_date: "2026-03-14",
    end_date: null,
    start_time: "18:00",
    end_time: "19:30",
    location: "RNHT Prayer Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-saturday",
    rsvp_enabled: false,
    rsvp_count: 0,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-4",
    title: "Yoga & Meditation Session",
    description:
      "Weekly yoga and meditation classes suitable for all levels. Guided by certified instructors combining traditional and modern techniques.",
    event_type: "class",
    start_date: "2026-03-15",
    end_date: null,
    start_time: "07:00",
    end_time: "08:30",
    location: "RNHT Community Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-sunday",
    rsvp_enabled: true,
    rsvp_count: 22,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-5",
    title: "Monthly Satyanarayana Vratam",
    description:
      "Join the community for the monthly Satyanarayana Pooja on Purnima (Full Moon) day. Katha recitation followed by maha prasadam.",
    event_type: "regular_pooja",
    start_date: "2026-03-25",
    end_date: null,
    start_time: "10:00",
    end_time: "12:30",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-purnima",
    rsvp_enabled: true,
    rsvp_count: 35,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-6",
    title: "Community Annadanam",
    description:
      "Monthly community meal service open to all. Volunteer to cook and serve or simply join us for a blessed meal.",
    event_type: "community",
    start_date: "2026-03-22",
    end_date: null,
    start_time: "12:00",
    end_time: "14:00",
    location: "RNHT Dining Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-4th-sunday",
    rsvp_enabled: true,
    rsvp_count: 60,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-7",
    title: "Hanuman Jayanti",
    description:
      "Grand celebration of Lord Hanuman's birth with special Abhishekam, Sundara Kandam Parayanam, and cultural events.",
    event_type: "festival",
    start_date: "2026-04-13",
    end_date: "2026-04-13",
    start_time: "06:00",
    end_time: "21:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 55,
    created_at: "2024-01-01T00:00:00.000Z",
  },
];

export const samplePanchangam = {
  date: "2024-01-01",
  location: "Austin, TX",
  sunrise: "6:22 AM",
  sunset: "6:01 PM",
  tithi: {
    name: "Dwadashi",
    start: "3:45 AM",
    end: "2:12 AM (next day)",
    paksha: "Shukla",
  },
  nakshatra: {
    name: "Pushya",
    start: "11:23 PM (prev day)",
    end: "10:45 PM",
  },
  yoga: {
    name: "Siddha",
    start: "6:15 AM",
    end: "4:33 AM (next day)",
  },
  karana: {
    name: "Baalava",
    start: "3:45 AM",
    end: "3:02 PM",
  },
  rahu_kalam: {
    start: "10:42 AM",
    end: "12:12 PM",
    warning: true,
  },
  yama_gandam: {
    start: "3:12 PM",
    end: "4:42 PM",
  },
  gulika_kalam: {
    start: "7:42 AM",
    end: "9:12 AM",
  },
  muhurtham: {
    name: "Amrut Kalam",
    start: "11:47 AM",
    end: "12:37 PM",
  },
  festival: null as { name: string; description: string } | null,
  vaara: "Wednesday",
  masa: "Phalguna",
  samvatsara: "Krodhana",
};
