import type { Service, ServiceCategory, Event } from "@/types/database";

export const sampleCategories: ServiceCategory[] = [
  {
    id: "cat-1",
    name: "Puja & Shanti",
    slug: "puja-shanti",
    description:
      "Purification, blessing, and auspicious pujas for homes, families, and milestones",
    icon: "🙏",
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-2",
    name: "Parayanam & Devotion",
    slug: "parayanam-devotion",
    description:
      "Sacred recitations and devotional observances rooted in Puranic and Vedic tradition",
    icon: "📿",
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-3",
    name: "Shraddham & Ancestor Rites",
    slug: "shraddham-ancestor-rites",
    description:
      "Traditional rites for honoring ancestors with Vaidika procedure and reverence",
    icon: "🪔",
    sort_order: 3,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-4",
    name: "Kalyanam & Weddings",
    slug: "kalyanam-weddings",
    description:
      "Divine weddings and auspicious ceremonial celebrations for deities and families",
    icon: "💒",
    sort_order: 4,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "cat-5",
    name: "Rudrabhishekam & Abhishekam",
    slug: "rudrabhishekam-abhishekam",
    description:
      "Elaborate Shiva worship, Vedic chant, and abhishekam traditions",
    icon: "🔥",
    sort_order: 5,
    created_at: "2024-01-01T00:00:00.000Z",
  },
];

export const sampleServices: Service[] = [
  {
    id: "svc-1",
    category_id: "cat-1",
    name: "UDAKA SHANTHI PUJA",
    slug: "udaka-shanthi-puja",
    short_description:
      "A powerful Vedic water purification ritual for peace, healing, graha dosha shanti, and spiritual balance.",
    full_description:
      "Udaka Shanti Puja is a powerful Vedic ritual in which sacred, mantra-charged water is used to pacify negative energies and restore peace, health, and harmony. It is performed for the removal of graha doshas, especially those related to Rahu, Ketu, and Shani, and is commonly observed after birth, before important life events, during difficult planetary periods, or following repeated obstacles or ill health. It is also performed for everyone's well-being after a death in the family, to remove ritual impurity, and for the purification of the body and house premises. The ritual includes sankalpam, kalasha sthapanam, and Vedic mantra recitation, sometimes accompanied by a shanti homa, after which the sanctified water is sprinkled for purification.",
    significance:
      "This puja is believed to cleanse the body, mind, and surroundings while bringing spiritual balance, protection, harmony, and lasting inner peace.",
    items_to_bring: [
      "Kalasham or vessel for sanctified water",
      "Mango leaves, coconut, and flowers",
      "Turmeric, kumkum, and fruits",
      "Any additional items advised by Panditji based on family or graha shanti needs",
    ],
    whats_included: [
      "Sankalpam and kalasha sthapanam",
      "Vedic mantra recitation for shanti and purification",
      "Sanctified water sprinkling for body and premises",
      "Optional shanti homa guidance when required",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 90,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-2",
    category_id: "cat-2",
    name: "DEVI SAPTASHATI PARAYANAM (DEVI MAHATMYA PATH) CHANDI PATH",
    slug: "devi-saptashati-parayanam",
    short_description:
      "A sacred Chandi Path of 700 verses invoking the Divine Mother for courage, protection, peace, and spiritual harmony.",
    full_description:
      "Durga Saptashati Path, also known as Devi Mahatmya or Chandi Path, is a sacred recitation of 700 verses that praise the Divine Mother as the supreme universal power behind creation, protection, and transformation. Preserved in the Markandeya Purana and central to the Shakta tradition, the text is divided into 13 chapters and three main sections describing the Mother's victory over forces representing ignorance, ego, desire, and subtle pride. Chandi Devi is worshipped here as both fierce and compassionate, destroying negativity and injustice while granting protection, strength, wisdom, and prosperity to her devotees. The path is traditionally performed with preparatory prayers such as sankalpa, nyasa, kavacha, argala, and keelaka, followed by complete recitation, making it a powerful spiritual discipline rather than just a story. It is especially observed during Navaratri, difficult phases of life, major transitions, and for family well-being.",
    significance:
      "This sacred path is believed to bring courage, peace, protection from unseen forces, removal of doshas, and both spiritual and material harmony through the grace of the Divine Mother.",
    items_to_bring: [
      "Kumkum, turmeric, and fresh flowers",
      "Fruits and naivedyam",
      "Devi photo or vigraham if performed at home",
      "Any additional puja samagri advised for Chandi Path observance",
    ],
    whats_included: [
      "Sankalpam and preparatory prayers",
      "Nyasa, kavacha, argala, and keelaka where observed",
      "Complete Devi Saptashati / Chandi Path recitation",
      "Devi upacharas, concluding prayers, and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-3",
    category_id: "cat-2",
    name: "SUNDARAKANDA PATH (PARAYANAM)",
    slug: "sundarakanda-path-parayanam",
    short_description:
      "A devotional recitation of Sundara Kanda invoking Hanuman’s courage, protection, clarity, and grace.",
    full_description:
      "Sundarakanda Path, or Sundara Kanda Parayanam, is the devotional recitation of the Sundara Kanda, a beautiful and powerful chapter of the Ramayana centered on Sri Hanuman's heroic journey to Lanka. It is called Sundara because it beautifully reveals pure bhakti joined with fearless action. In this sacred episode, Hanuman discovers Sita Mata, gives her hope, and delivers Sri Rama's message. Every verse radiates courage, clarity, devotion, and grace, making this parayanam especially beloved during difficult periods, major undertakings, and devotional observances.",
    significance:
      "Devotees associate Sundarakanda Path with the removal of obstacles and fear, mental strength and focus, protection from negativity, Saturn dosha relief, and the blessings of Hanuman and Sri Rama.",
    items_to_bring: [
      "Hanuman or Sri Rama photo or vigraham",
      "Flowers, betel leaves, and fruits",
      "Naivedyam and ghee lamp",
      "Any additional devotional items advised by Panditji",
    ],
    whats_included: [
      "Sankalpam",
      "Complete or guided Sundarakanda recitation",
      "Hanuman and Sri Rama prayers",
      "Mangala harati and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 150,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-4",
    category_id: "cat-3",
    name: "ANNA SHRADHAM (ANCESTRAL PRAYERS)",
    slug: "anna-shraddham",
    short_description:
      "A Vaidika Pitru-karma performed with sacred discipline for ancestral satisfaction, blessings, and lineage continuity.",
    full_description:
      "Anna Shraddham is a Vaidika Pitru-karma enjoined in the Dharmashastras, Grihya Sutras, and Smriti texts for the propitiation of the Pitrs and the discharge of Pitru-rina, the ancestral obligation incumbent upon the householder. Classified as a nitya-naimittika karma, it is performed with sankalpam, pinda-pradana, anna-nivedana, tilodaka-dana, and dakshina, in conformity with scriptural injunction and inherited ritual discipline. The shastras affirm that through proper Shraddha, the Pitrs attain tripti and shanti, bestow their anugraha upon descendants, and ensure continuity of lineage, prosperity, and spiritual stability, thereby sustaining rta, the cosmic order upheld by dharma. The fruit of Anna Shraddham arises not from external elaboration, but from precision of rite, purity of intent, and unwavering adherence to sacred law.",
    significance:
      "This sacred observance is performed for Pitru tripti, blessings of the ancestors, increase in longevity, continuity of lineage, prosperity, and spiritual steadiness within the household.",
    items_to_bring: [
      "Cooked offering materials as advised by Panditji",
      "Sesame seeds, darbha, and tilodaka materials",
      "Vastra, dakshina, and ritual vessels",
      "Banana leaves, fruits, and betel leaves",
    ],
    whats_included: [
      "Sankalpam and full Shraddha vidhi guidance",
      "Pinda-pradana and anna-nivedana",
      "Tilodaka-dana and Pitru-karya observance",
      "Concluding blessings in accordance with family tradition",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-5",
    category_id: "cat-3",
    name: "HIRANYA SHRADHAM (ANCESTORAL OFFERING)",
    slug: "hiranya-shraddham",
    short_description:
      "A sacred Vaidika ancestral observance performed through sankalpam, mantra, and dana for Pitru grace and lineage protection.",
    full_description:
      "Human birth is not an isolated event; our body, lineage, values, and the very opportunity to live this life arise from the blessings of our ancestors, and therefore the scriptures declare that honoring them is a sacred duty. The Vedic teaching 'Matridevo bhava, Pitridevo bhava' and the doctrine of the three debts affirm that Pitru-rina is discharged only through Shraddha and sincere remembrance. Recognizing this truth, the shastras approve Hiranya Shraddham as a complete and valid form of ancestral observance, fulfilled through sincere sankalpam, remembrance of the lineage, focused mantra recitation, and dakshina or charitable offerings made in the name of the Pitrs. When ancestors are remembered with reverence and devotion, harmony is maintained within the family, health and lineage continuity are protected, obstacles are reduced, and unseen blessings begin to flow. This observance is not about dwelling on death, but about honoring the source of our life and remaining connected to our roots through gratitude, humility, responsibility, and devotion.",
    significance:
      "Hiranya Shraddham is performed for Pitru satisfaction, family harmony, removal of obstacles, lineage continuity, and the sustaining blessings of the ancestors upon present and future generations.",
    items_to_bring: [
      "Sesame seeds and darbha",
      "Dakshina or hiranya offering",
      "Fruits, betel leaves, and simple naivedyam",
      "Any required ritual items as advised by Panditji",
    ],
    whats_included: [
      "Sankalpam with lineage remembrance",
      "Pitru mantra recitation and observance guidance",
      "Hiranya-based offering and dana procedure",
      "Closing prayers and blessings in accordance with family tradition",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 120,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-6",
    category_id: "cat-4",
    name: "SHIVA PARVATI KALYANAM (CELESTIAL WEDDING CEREMONY OF SHIVA AND PARVATI)",
    slug: "shiva-parvati-kalyanam",
    short_description:
      "A divine kalyanam celebrating the sacred union of Shiva and Parvati as love, balance, devotion, and cosmic harmony.",
    full_description:
      "According to the Puranas, the love of Shiva and Parvati unfolds through grief, longing, and unshakable devotion. After Sati's self-immolation, Shiva withdraws into fierce detachment, and creation itself is thrown out of balance. Parvati, carrying the soul-memory of Sati, approaches Shiva not with impatience but with quiet perseverance, embracing tapasya, faith, and compassion that understands his pain rather than trying to erase it. When Shiva finally accepts her, their marriage restores harmony to creation, proving that supreme detachment and supreme love are not contradictions but complements. Celebrated on Mount Kailasa, with Brahma performing the sacred rites and Vishnu offering blessings, this divine union establishes cosmic balance and leads to the birth of Ganesha and Kartikeya. Shiva Parvati Kalyanam teaches that true partnership rests upon equality, patience, and shared purpose, and that spiritual awakening is fulfilled not by rejecting life, but by embracing it with responsibility, compassion, and inner steadiness.",
    significance:
      "This kalyanam is performed for marital harmony, family wellbeing, shared purpose in household life, and the blessings of Shiva and Parvati upon relationships, dharma, and inner balance.",
    items_to_bring: [
      "Flowers, garlands, fruits, and coconuts",
      "Naivedyam offerings and mangalya items as advised",
      "New vastram for deities if desired",
      "Any additional kalyana samagri recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and full kalyana vidhi",
      "Complete Shiva Parvati Kalyanam procedure",
      "Mangalya, talambralu, and auspicious ceremonial observances",
      "Harati, blessings, and prasadam",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-7",
    category_id: "cat-5",
    name: "MAHANYASA PURVAKA EKADASA RUDRABHISHEKAM",
    slug: "mahanyasa-purvaka-ekadasa-rudrabhishekam",
    short_description:
      "A powerful Shaiva ritual combining Mahanyasa with 11-fold Rudrabhishekam and full Sri Rudram chanting.",
    full_description:
      "Mahanyasa Purvaka Ekadasa Rudrabhishekam is one of the most powerful and complete Shaiva rituals, combining Mahanyasa with Ekadasa, or 11-fold, Rudrabhishekam to invoke Lord Shiva in all His cosmic forms. Mahanyasa is an elaborate Vedic purification and consecration of the body using mantras from Sri Rudram, preparing both the priest and the ritual space by aligning body, mind, and prana with Rudra-tattva before worship begins. Ekadasa Rudrabhishekam means the Shiva Linga is worshipped with 11 complete Rudrabhishekams, representing the 11 Rudras, the 11 senses, and the 11 forms of cosmic energy. Each abhishekam is accompanied by full chanting of Namakam and Chamakam. The ritual includes sankalpam, Mahanyasa, Kara-Anga Nyasa, abhishekams with sacred substances such as water, milk, curd, honey, ghee, sugarcane juice, coconut water, panchamrita, and special herbal waters, followed by arati and prasada vitarana.",
    significance:
      "This sacred ritual is believed to remove negative karma and deep-rooted obstacles, bring mental peace and emotional healing, support health and longevity, promote family harmony, and grant Shiva anugraha for both material and spiritual upliftment.",
    items_to_bring: [
      "Flowers, bilva leaves, and naivedyam offerings",
      "Milk, curd, honey, ghee, and fruits",
      "Panchamrita and special abhisheka dravyas as advised",
      "Any additional Shiva puja samagri recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and Mahanyasa purvaka purification",
      "Kara-Anga Nyasa and Sri Rudram chanting",
      "11-fold Rudrabhishekam with sacred substances",
      "Harati, prasada vitarana, and concluding blessings",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 210,
    location_type: "both",
    is_active: true,
    sort_order: 1,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "svc-8",
    category_id: "cat-4",
    name: "SRI SEETA RAMA KALYANAM (CELESTIAL WEDDING CEREMONY OF SEETA RAMA)",
    slug: "sri-seeta-rama-kalyanam",
    short_description:
      "A sacred kalyanam celebrating Seeta and Rama as the ideal union of dharma, devotion, virtue, and shared responsibility.",
    full_description:
      "Seeta Rama Kalyanam, the divine wedding of Sree Seeta and Lord Sree Rama, holds deep spiritual and human significance as it presents the ideal model of marriage rooted in righteousness, mutual respect, and unwavering commitment. This sacred union teaches that marriage is not merely a social bond but a lifelong spiritual journey in which two souls walk together on the path of dharma. Rama represents truth, duty, and moral discipline, while Sita stands for purity, inner strength, patience, and devotion; together they show how harmony is achieved through balance, sacrifice, and understanding. Their wedding reminds humanity that love must be guided by values, not desire, and strength must be guided by humility. Sita is revered as sahadharmacharini, Rama's equal partner in dharma, and this divine kalyanam continues to inspire generations toward virtue, faith, shared responsibility, and auspicious family life.",
    significance:
      "This kalyanam is performed for marital harmony, auspiciousness, prosperity, spiritual fulfillment, and the blessings of Seeta and Rama upon family life guided by dharma.",
    items_to_bring: [
      "Flowers, fruits, coconuts, and naivedyam offerings",
      "Garlands, mangalya items, and kalyana samagri as advised",
      "New vastram for the deities if desired",
      "Any additional offerings recommended by Panditji",
    ],
    whats_included: [
      "Sankalpam and complete kalyana preparations",
      "Full Sri Seeta Rama Kalyanam procedure",
      "Mangala harati, blessings, and prasadam",
      "Auspicious family blessings in the spirit of dharma",
    ],
    image_url: null,
    price: null,
    price_type: "custom",
    price_tiers: null,
    suggested_donation: null,
    duration_minutes: 180,
    location_type: "both",
    is_active: true,
    sort_order: 2,
    created_at: "2024-01-01T00:00:00.000Z",
    updated_at: "2024-01-01T00:00:00.000Z",
  },
];

export const sampleEvents: Event[] = [
  {
    id: "evt-1",
    title: "Ugadi Celebrations 2026",
    description:
      "Telugu and Kannada New Year celebrations with special poojas, cultural programs, and festive feast. Join us for Panchangam Sravanam and Ugadi Pachadi distribution.",
    event_type: "festival",
    start_date: "2026-03-29",
    end_date: "2026-03-29",
    start_time: "09:00",
    end_time: "14:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 45,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-2",
    title: "Sri Rama Navami",
    description:
      "Celebration of Lord Rama's birth with Sita Rama Kalyanotsavam, Abhishekam, and special cultural programs throughout the day.",
    event_type: "festival",
    start_date: "2026-04-07",
    end_date: "2026-04-07",
    start_time: "08:00",
    end_time: "20:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 78,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-3",
    title: "Weekly Bhajan Sandhya",
    description:
      "Join us every Saturday evening for devotional bhajans and kirtans. All are welcome to participate and immerse in the divine melodies.",
    event_type: "regular_pooja",
    start_date: "2026-03-14",
    end_date: null,
    start_time: "18:00",
    end_time: "19:30",
    location: "RNHT Prayer Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-saturday",
    rsvp_enabled: false,
    rsvp_count: 0,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-4",
    title: "Yoga & Meditation Session",
    description:
      "Weekly yoga and meditation classes suitable for all levels. Guided by certified instructors combining traditional and modern techniques.",
    event_type: "class",
    start_date: "2026-03-15",
    end_date: null,
    start_time: "07:00",
    end_time: "08:30",
    location: "RNHT Community Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "weekly-sunday",
    rsvp_enabled: true,
    rsvp_count: 22,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-5",
    title: "Monthly Satyanarayana Vratam",
    description:
      "Join the community for the monthly Satyanarayana Pooja on Purnima (Full Moon) day. Katha recitation followed by maha prasadam.",
    event_type: "regular_pooja",
    start_date: "2026-03-25",
    end_date: null,
    start_time: "10:00",
    end_time: "12:30",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-purnima",
    rsvp_enabled: true,
    rsvp_count: 35,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-6",
    title: "Community Annadanam",
    description:
      "Monthly community meal service open to all. Volunteer to cook and serve or simply join us for a blessed meal.",
    event_type: "community",
    start_date: "2026-03-22",
    end_date: null,
    start_time: "12:00",
    end_time: "14:00",
    location: "RNHT Dining Hall",
    image_url: null,
    is_recurring: true,
    recurrence_rule: "monthly-4th-sunday",
    rsvp_enabled: true,
    rsvp_count: 60,
    created_at: "2024-01-01T00:00:00.000Z",
  },
  {
    id: "evt-7",
    title: "Hanuman Jayanti",
    description:
      "Grand celebration of Lord Hanuman's birth with special Abhishekam, Sundara Kandam Parayanam, and cultural events.",
    event_type: "festival",
    start_date: "2026-04-13",
    end_date: "2026-04-13",
    start_time: "06:00",
    end_time: "21:00",
    location: "RNHT Main Temple Hall",
    image_url: null,
    is_recurring: false,
    recurrence_rule: null,
    rsvp_enabled: true,
    rsvp_count: 55,
    created_at: "2024-01-01T00:00:00.000Z",
  },
];

export const samplePanchangam = {
  date: "2024-01-01",
  location: "Austin, TX",
  sunrise: "6:22 AM",
  sunset: "6:01 PM",
  tithi: {
    name: "Dwadashi",
    start: "3:45 AM",
    end: "2:12 AM (next day)",
    paksha: "Shukla",
  },
  nakshatra: {
    name: "Pushya",
    start: "11:23 PM (prev day)",
    end: "10:45 PM",
  },
  yoga: {
    name: "Siddha",
    start: "6:15 AM",
    end: "4:33 AM (next day)",
  },
  karana: {
    name: "Baalava",
    start: "3:45 AM",
    end: "3:02 PM",
  },
  rahu_kalam: {
    start: "10:42 AM",
    end: "12:12 PM",
    warning: true,
  },
  yama_gandam: {
    start: "3:12 PM",
    end: "4:42 PM",
  },
  gulika_kalam: {
    start: "7:42 AM",
    end: "9:12 AM",
  },
  muhurtham: {
    name: "Abhijit Muhurtham",
    start: "11:47 AM",
    end: "12:37 PM",
  },
  festival: null as { name: string; description: string } | null,
  vaara: "Wednesday",
  masa: "Phalguna",
  samvatsara: "Krodhana",
};
